################################################################################
MLI_FILE		= cordova_media.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-media
################################################################################
